// <auto-generated />
namespace InvoiceManagerMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NextUpdate11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NextUpdate11));
        
        string IMigrationMetadata.Id
        {
            get { return "202308072021297_NextUpdate1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
